services:
  - type: web
    name: sv94-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn sv94:app --bind 0.0.0.0:$PORT
    envVars:
      - key: LINE_ACCESS_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.11
